AllCops:
  NewCops: enable
  Include:
    - '**/*.rb'
    - '**/*.pryrc'
    - '**/*.rake'
    - '.env'
    - '.simplecov'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'tmp/**/*'
    - 'lib/.git/**/*'
    - 'db/**/*'
    - 'db/migrate/**'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'railroader/**/*'
    - '.pryrc'
    - 'license_okay'
Layout/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 50