require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-graphql

AllCops:
  NewCops: enable
  Include:
    - '**/*.rb'
    - '**/*.pryrc'
    - '**/*.rake'
    - '.env'
    - '.simplecov'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
  Exclude:
    - 'tmp/**/*'
    - 'lib/.git/**/*'
    - 'db/**/*'
    - 'db/migrate/**'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'railroader/**/*'
    - '.pryrc'
    - 'license_okay'
Layout/LineLength:
  Max: 200
Metrics/MethodLength:
  Max: 50
GraphQL/FieldDescription:
  Enabled: false
GraphQL/ArgumentDescription:
  Enabled: false
GraphQL/ObjectDescription:
  Enabled: false
GraphQL/ExtractType:
  Enabled: false
Metrics/BlockLength:
  Max: 250
RSpec/SubjectStub:
  Enabled: false
GraphQL/ExtractInputType:
  MaxArguments: 8